<?php
// Cấu hình CRUD: mỗi resource mô tả bảng, khóa chính, field form và cột hiển thị trên danh sách.
return [
            'ThanhVien' => [
                'table' => 'ThanhVien',
                'pk' => ['MaThanhVien'],
                'title' => 'Thành viên',
                'fields' => [
                    'MaThanhVien' => ['label' => 'Mã số', 'type' => 'text', 'required' => true, 'max_length' => 50],
                    'HoTen' => ['label' => 'Họ tên', 'type' => 'text', 'required' => true, 'max_length' => 100],
                    'Email' => ['label' => 'Email', 'type' => 'email', 'required' => true, 'max_length' => 100],
                    'MatKhau' => ['label' => 'Mật khẩu', 'type' => 'text', 'required' => true, 'max_length' => 255],
                    'MaVaiTro' => ['label' => 'Vai trò', 'type' => 'select', 'relation' => ['table' => 'VaiTro', 'value' => 'MaVaiTro', 'label' => 'TenVaiTro'], 'required' => true],
                    'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
                ],
                'list' => ['MaThanhVien' => 'Mã số', 'HoTen' => 'Họ tên', 'Email' => 'Email', 'MatKhau' => 'Mật khẩu', 'TenVaiTro' => 'Vai trò', 'NgayTao' => 'Ngày tạo'],
            ],
            'CLB' => [
                'table' => 'CLB',
                'pk' => ['MaCLB'],
                'title' => 'Câu lạc bộ',
                'fields' => [
                    'MaCLB' => ['label' => 'Mã CLB', 'type' => 'text', 'required' => true, 'max_length' => 50],
                    'TenCLB' => ['label' => 'Tên CLB', 'type' => 'text', 'required' => true, 'max_length' => 150],
                    'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea'],
                    'ChuNhiem' => ['label' => 'Chủ nhiệm', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'nullable' => true],
                    'NgayThanhLap' => ['label' => 'Ngày thành lập', 'type' => 'date', 'nullable' => true],
                ],
                'list' => ['MaCLB' => 'Mã CLB', 'TenCLB' => 'Tên CLB', 'ChuNhiemTen' => 'Chủ nhiệm', 'NgayThanhLap' => 'Ngày thành lập', 'MoTa' => 'Mô tả'],
            ],
            'ThanhVienCLB' => [
                'table' => 'ThanhVienCLB',
                'pk' => ['MaCLB', 'MaThanhVien'],
                'title' => 'Thành viên CLB',
                'fields' => [
                    'MaCLB' => ['label' => 'CLB', 'type' => 'select', 'relation' => ['table' => 'CLB', 'value' => 'MaCLB', 'label' => 'TenCLB'], 'required' => true],
                    'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'VaiTroCLB' => ['label' => 'Vai trò trong CLB', 'type' => 'select_static', 'options' => ['Chủ nhiệm' => 'Chủ nhiệm', 'Ban tổ chức' => 'Ban tổ chức', 'Thành viên' => 'Thành viên'], 'required' => true],
                    'NgayThamGia' => ['label' => 'Ngày tham gia', 'type' => 'datetime'],
                ],
                'list' => ['TenCLB' => 'CLB', 'HoTen' => 'Thành viên', 'Email' => 'Email', 'VaiTroCLB' => 'Vai trò CLB', 'NgayThamGia' => 'Ngày tham gia'],
            ],
            'SuKien' => [
                'table' => 'SuKien',
                'pk' => ['MaSuKien'],
                'title' => 'Sự kiện',
                'fields' => [
                    'MaSuKien' => ['label' => 'Mã sự kiện', 'type' => 'text', 'required' => true, 'max_length' => 50],
                    'TenSuKien' => ['label' => 'Tên sự kiện', 'type' => 'text', 'required' => true, 'max_length' => 100],
                    'MaCLB' => ['label' => 'CLB tổ chức', 'type' => 'select', 'relation' => ['table' => 'CLB', 'value' => 'MaCLB', 'label' => 'TenCLB'], 'required' => true],
                    'MaLoaiSuKien' => ['label' => 'Loại sự kiện', 'type' => 'select', 'relation' => ['table' => 'LoaiSuKien', 'value' => 'MaLoaiSuKien', 'label' => 'TenLoaiSuKien'], 'required' => true],
                    'HocKy' => ['label' => 'Học kỳ', 'type' => 'select_static', 'options' => ['HK1' => 'HK1', 'HK2' => 'HK2', 'HK3' => 'HK3'], 'required' => true],
                    'NamHoc' => ['label' => 'Năm học', 'type' => 'text', 'required' => true, 'pattern' => '/^\d{4}-\d{4}$/'],
                    'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea'],
                    'NgayBatDau' => ['label' => 'Ngày bắt đầu', 'type' => 'datetime', 'required' => true],
                    'NgayKetThuc' => ['label' => 'Ngày kết thúc', 'type' => 'datetime', 'required' => true],
                    'NguoiToChuc' => ['label' => 'Người tổ chức', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'SucChua' => ['label' => 'Sức chứa', 'type' => 'number', 'required' => true, 'min' => 1],
                    'CheckinMoLuc' => ['label' => 'QR mở lúc', 'type' => 'datetime', 'required' => true],
                    'CheckinDongLuc' => ['label' => 'QR đóng lúc', 'type' => 'datetime', 'required' => true],
                ],
                'list' => ['MaSuKien' => 'Mã sự kiện', 'TenSuKien' => 'Tên sự kiện', 'TenCLB' => 'CLB', 'TenLoaiSuKien' => 'Loại', 'HocKy' => 'Học kỳ', 'NamHoc' => 'Năm học', 'SucChua' => 'Sức chứa', 'SoDangKy' => 'Đã đăng ký', 'SoCheckin' => 'Đã check-in', 'SoChoConLai' => 'Còn chỗ', 'NgayBatDau' => 'Bắt đầu', 'NgayKetThuc' => 'Kết thúc', 'CheckinMoLuc' => 'QR mở', 'CheckinDongLuc' => 'QR đóng'],
            ],
            'NhomHocTap' => [
                'table' => 'NhomHocTap',
                'pk' => ['MaNhom'],
                'title' => 'Nhóm học tập',
                'fields' => [
                    'MaNhom' => ['label' => 'Mã nhóm', 'type' => 'text', 'required' => true, 'max_length' => 50],
                    'TenNhom' => ['label' => 'Tên nhóm', 'type' => 'text', 'required' => true, 'max_length' => 100],
                    'TroGiang' => ['label' => 'Trợ giảng', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
                    'MoTa' => ['label' => 'Mô tả', 'type' => 'textarea'],
                ],
                'list' => ['MaNhom' => 'Mã nhóm', 'TenNhom' => 'Tên nhóm', 'TroGiangTen' => 'Trợ giảng', 'NgayTao' => 'Ngày tạo', 'MoTa' => 'Mô tả'],
            ],
            'BaiDang' => [
                'table' => 'BaiDang',
                'pk' => ['MaBaiDang'],
                'title' => 'Bài đăng',
                'fields' => [
                    'MaBaiDang' => ['label' => 'Mã bài đăng', 'type' => 'text', 'required' => true, 'max_length' => 50],
                    'TieuDe' => ['label' => 'Tiêu đề', 'type' => 'text', 'required' => true, 'max_length' => 255],
                    'Anh' => ['label' => 'Ảnh', 'type' => 'image', 'required' => true],
                    'NoiDung' => ['label' => 'Nội dung', 'type' => 'textarea', 'required' => true],
                    'TacGia' => ['label' => 'Tác giả', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'NgayTao' => ['label' => 'Ngày tạo', 'type' => 'datetime'],
                ],
                'list' => ['MaBaiDang' => 'Mã', 'TieuDe' => 'Tiêu đề', 'Anh' => 'Ảnh', 'NoiDung' => 'Nội dung', 'TacGiaTen' => 'Tác giả', 'NgayTao' => 'Ngày tạo'],
            ],
            'ThanhVienSuKien' => [
                'table' => 'ThanhVienSuKien',
                'pk' => ['MaSuKien', 'MaThanhVien'],
                'title' => 'Thành viên tham gia sự kiện',
                'ajaxConfirm' => true,
                'fields' => [
                    'MaSuKien' => ['label' => 'Sự kiện', 'type' => 'select', 'relation' => ['table' => 'SuKien', 'value' => 'MaSuKien', 'label' => 'TenSuKien'], 'required' => true],
                    'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'NgayDangKy' => ['label' => 'Ngày đăng ký', 'type' => 'datetime'],
                    'TrangThaiThamGia' => ['label' => 'Trạng thái tham gia', 'type' => 'select_static', 'options' => ['Đã đăng ký' => 'Đã đăng ký', 'Đã tham gia' => 'Đã tham gia', 'Vắng' => 'Vắng', 'Đã hủy' => 'Đã hủy'], 'required' => true],
                    'NgayXacNhan' => ['label' => 'Ngày xác nhận', 'type' => 'datetime', 'nullable' => true],
                    'XacNhanBoi' => ['label' => 'Xác nhận bởi', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'nullable' => true],
                ],
                'list' => ['TenSuKien' => 'Sự kiện', 'HoTen' => 'Thành viên', 'NgayDangKy' => 'Ngày đăng ký', 'TrangThaiThamGia' => 'Trạng thái', 'NgayXacNhan' => 'Ngày xác nhận', 'XacNhanBoiTen' => 'Xác nhận bởi'],
            ],
            'CheckinSuKien' => [
                'table' => 'CheckinSuKien',
                'pk' => ['MaCheckin'],
                'auto' => ['MaCheckin'],
                'title' => 'Log check-in sự kiện',
                'fields' => [
                    'MaCheckin' => ['label' => 'Mã check-in', 'type' => 'number', 'readonly' => true],
                    'MaSuKien' => ['label' => 'Sự kiện', 'type' => 'select', 'relation' => ['table' => 'SuKien', 'value' => 'MaSuKien', 'label' => 'TenSuKien'], 'required' => true],
                    'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'ThoiGianCheckin' => ['label' => 'Thời gian check-in', 'type' => 'datetime'],
                    'PhuongThuc' => ['label' => 'Phương thức', 'type' => 'select_static', 'options' => ['QR' => 'QR', 'Thủ công' => 'Thủ công'], 'required' => true],
                    'XacNhanBoi' => ['label' => 'Xác nhận bởi', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'nullable' => true],
                ],
                'list' => ['MaCheckin' => 'Mã', 'TenSuKien' => 'Sự kiện', 'TenCLB' => 'CLB', 'HoTen' => 'Sinh viên', 'ThoiGianCheckin' => 'Thời gian', 'PhuongThuc' => 'Phương thức', 'XacNhanBoiTen' => 'Xác nhận bởi'],
            ],
            'QuyTacDiemRenLuyen' => [
                'table' => 'QuyTacDiemRenLuyen',
                'pk' => ['MaQuyTac'],
                'auto' => ['MaQuyTac'],
                'title' => 'Quy tắc điểm rèn luyện',
                'fields' => [
                    'MaQuyTac' => ['label' => 'Mã quy tắc', 'type' => 'number', 'readonly' => true],
                    'MaLoaiSuKien' => ['label' => 'Loại sự kiện', 'type' => 'select', 'relation' => ['table' => 'LoaiSuKien', 'value' => 'MaLoaiSuKien', 'label' => 'TenLoaiSuKien'], 'required' => true],
                    'HocKy' => ['label' => 'Học kỳ', 'type' => 'select_static', 'options' => ['HK1' => 'HK1', 'HK2' => 'HK2', 'HK3' => 'HK3'], 'required' => true],
                    'NamHoc' => ['label' => 'Năm học', 'type' => 'text', 'required' => true, 'pattern' => '/^\d{4}-\d{4}$/'],
                    'Diem' => ['label' => 'Điểm', 'type' => 'number', 'required' => true, 'min' => 0],
                    'GhiChu' => ['label' => 'Ghi chú', 'type' => 'textarea'],
                ],
                'list' => ['MaQuyTac' => 'Mã', 'TenLoaiSuKien' => 'Loại sự kiện', 'HocKy' => 'Học kỳ', 'NamHoc' => 'Năm học', 'Diem' => 'Điểm', 'GhiChu' => 'Ghi chú'],
            ],
            'DiemRenLuyen' => [
                'table' => 'DiemRenLuyen',
                'pk' => ['MaDiem'],
                'auto' => ['MaDiem'],
                'title' => 'Điểm rèn luyện',
                'fields' => [
                    'MaDiem' => ['label' => 'Mã điểm', 'type' => 'number', 'readonly' => true],
                    'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'MaSuKien' => ['label' => 'Sự kiện', 'type' => 'select', 'relation' => ['table' => 'SuKien', 'value' => 'MaSuKien', 'label' => 'TenSuKien'], 'required' => true],
                    'MaQuyTac' => ['label' => 'Quy tắc điểm', 'type' => 'select', 'relation' => ['table' => 'QuyTacDiemRenLuyen', 'value' => 'MaQuyTac', 'label' => 'MaQuyTac'], 'required' => true],
                    'HocKy' => ['label' => 'Học kỳ', 'type' => 'select_static', 'options' => ['HK1' => 'HK1', 'HK2' => 'HK2', 'HK3' => 'HK3'], 'required' => true],
                    'NamHoc' => ['label' => 'Năm học', 'type' => 'text', 'required' => true, 'pattern' => '/^\d{4}-\d{4}$/'],
                    'SoDiem' => ['label' => 'Số điểm', 'type' => 'number', 'required' => true, 'min' => 0],
                    'NgayCong' => ['label' => 'Ngày cộng', 'type' => 'datetime'],
                    'GhiChu' => ['label' => 'Ghi chú', 'type' => 'textarea'],
                ],
                'list' => ['MaDiem' => 'Mã', 'HoTen' => 'Thành viên', 'TenSuKien' => 'Sự kiện', 'HocKy' => 'Học kỳ', 'NamHoc' => 'Năm học', 'SoDiem' => 'Điểm', 'NgayCong' => 'Ngày cộng', 'GhiChu' => 'Ghi chú'],
            ],
            'TongDiemRenLuyen' => [
                'table' => 'TongDiemRenLuyen',
                'pk' => ['MaTongDiem'],
                'auto' => ['MaTongDiem'],
                'title' => 'Tổng điểm rèn luyện',
                'fields' => [
                    'MaTongDiem' => ['label' => 'Mã tổng điểm', 'type' => 'number', 'readonly' => true],
                    'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'HocKy' => ['label' => 'Học kỳ', 'type' => 'select_static', 'options' => ['HK1' => 'HK1', 'HK2' => 'HK2', 'HK3' => 'HK3'], 'required' => true],
                    'NamHoc' => ['label' => 'Năm học', 'type' => 'text', 'required' => true, 'pattern' => '/^\d{4}-\d{4}$/'],
                    'TongDiem' => ['label' => 'Tổng điểm', 'type' => 'number', 'required' => true, 'min' => 0],
                    'CapNhatLuc' => ['label' => 'Cập nhật lúc', 'type' => 'datetime'],
                ],
                'list' => ['MaTongDiem' => 'Mã', 'HoTen' => 'Thành viên', 'HocKy' => 'Học kỳ', 'NamHoc' => 'Năm học', 'TongDiem' => 'Tổng điểm', 'CapNhatLuc' => 'Cập nhật lúc'],
            ],
            'ChungNhan' => [
                'table' => 'ChungNhan',
                'pk' => ['MaChungNhan'],
                'title' => 'Chứng nhận',
                'fields' => [
                    'MaChungNhan' => ['label' => 'Mã chứng nhận', 'type' => 'text', 'required' => true, 'max_length' => 100],
                    'MaSuKien' => ['label' => 'Sự kiện', 'type' => 'select', 'relation' => ['table' => 'SuKien', 'value' => 'MaSuKien', 'label' => 'TenSuKien'], 'required' => true],
                    'MaThanhVien' => ['label' => 'Thành viên', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'NgayCap' => ['label' => 'Ngày cấp', 'type' => 'datetime'],
                    'NoiDung' => ['label' => 'Nội dung', 'type' => 'textarea', 'required' => true],
                    'CapBoi' => ['label' => 'Cấp bởi', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'nullable' => true],
                ],
                'list' => ['MaChungNhan' => 'Mã chứng nhận', 'TenSuKien' => 'Sự kiện', 'HoTen' => 'Thành viên', 'NgayCap' => 'Ngày cấp', 'NoiDung' => 'Nội dung', 'CapBoiTen' => 'Cấp bởi'],
            ],
            'BaoCao' => [
                'table' => 'BaoCao',
                'pk' => ['MaBaoCao'],
                'auto' => ['MaBaoCao'],
                'title' => 'Báo cáo',
                'fields' => [
                    'MaBaoCao' => ['label' => 'Mã báo cáo', 'type' => 'number', 'readonly' => true],
                    'TieuDe' => ['label' => 'Tiêu đề', 'type' => 'text', 'required' => true, 'max_length' => 100],
                    'NoiDung' => ['label' => 'Nội dung', 'type' => 'textarea', 'required' => true],
                    'NopBoi' => ['label' => 'Nộp bởi', 'type' => 'select', 'relation' => ['table' => 'ThanhVien', 'value' => 'MaThanhVien', 'label' => 'HoTen'], 'required' => true],
                    'NgayNop' => ['label' => 'Ngày nộp', 'type' => 'datetime'],
                ],
                'list' => ['MaBaoCao' => 'Mã', 'TieuDe' => 'Tiêu đề', 'NoiDung' => 'Nội dung', 'NopBoiTen' => 'Nộp bởi', 'NgayNop' => 'Ngày nộp'],
            ],
        ];
